title: codegod100.github.io
description: Personal website of codegod100.
baseurl: ""
url: "https://codegod100.github.io"

github_username: codegod100

theme: minima

# Required plugins for Minima v3
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/codegod100"
  skin: dark
