title: Roc Zulip Summaries
description: Daily activity summaries from the Roc language community on Zulip.
baseurl: ""
url: "https://codegod100.github.io"

github_username: codegod100

theme: minima
plugins:
  - jekyll-feed

# Simplified footer and header settings
minima:
  social_links:
    - { platform: github, user: codegod100 }
