title: codegod100.github.io
description: Personal website of codegod100.
baseurl: ""
url: "https://codegod100.github.io"

github_username: codegod100

theme: minima
plugins:

minima:
  social_links:
    - { platform: github, user: codegod100 }
